### ISSUE TITLE
zero pvalue

### ISSUE THREAD

**Issue by guoxueyu** [LiYouBioinfo/DELTA-Toolkit#1]
hi sorry to bother you:

how about to perform Eq.4 when the P_feature in Eq.3 is zero, cause there is no way to do the log transformation for 0 ?

best,
guo

**Comment by LiYouBioinfo** [comment]
Hi. You may combine Eq2-4 to perform the log transformation (i.e., log(x*y)=log(x)+log(y)) to avoid any round-up operations introduced by the programing language. I believe the actual value of P_feature should not be zero cause the numerator of Eq.2 will not be zero. 

Equations refered in this answer can be found in the supplementary document of this study: https://doi.org/10.1093/nar/gkac173
